# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vame <marvin@42.fr>                        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2014/11/10 16:31:28 by vame              #+#    #+#              #
#    Updated: 2015/05/02 18:24:03 by skerkour         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

INC = libft.h

CFLAGS = -Wall -Wextra -Werror

SRC = ./ft_abs.c ./ft_atoi.c ./ft_bzero.c ./ft_isalnum.c \
	  ./ft_isalpha.c ./ft_isascii.c ./ft_isdigit.c \
	  ./ft_islower.c ./ft_isprint.c ./ft_isupper.c \
	  ./ft_itoa.c ./ft_memalloc.c ./ft_memccpy.c \
	  ./ft_memchr.c ./ft_memcmp.c ./ft_memcpy.c \
	  ./ft_memdel.c ./ft_memmove.c ./ft_memset.c \
	  ./ft_putchar.c ./ft_putchar_fd.c ./ft_putendl.c \
	  ./ft_putendl_fd.c ./ft_putnbr_fd.c ./ft_putnbr.c \
	  ./ft_putstr_fd.c ./ft_putstr.c ./ft_strcat.c \
	  ./ft_strchr.c ./ft_strclr.c ./ft_strcmp.c ./ft_atoi_l.c ./ft_lstiter_r.c \
	  ./ft_strcpy.c ./ft_strdel.c ./ft_strdup.c ./ft_max.c ./ft_min.c \
	  ./ft_strequ.c ./ft_striter.c ./ft_striteri.c ./ft_max_db.c ./ft_min_db.c \
	  ./ft_strjoin.c ./ft_strlcat.c ./ft_strlen.c ./ft_abs_db.c \
	  ./ft_strmap.c ./ft_strmapi.c ./ft_strncat.c ./ft_color_degrade.c \
	  ./ft_strncmp.c ./ft_strncpy.c ./ft_strnequ.c ./ft_nbrsplit.c \
	  ./ft_strnew.c ./ft_strnstr.c ./ft_strrchr.c ./ft_strsplit_esc.c \
	  ./ft_strstr.c ./ft_strsub.c ./ft_lstmap.c ./ft_strlen_c.c\
	  ./ft_strtrim.c ./ft_tolower.c ./ft_toupper.c ./ft_strdel_double.c \
	  ./ft_lstnew.c ./ft_lstdelone.c ./ft_lstdel.c ./ft_itoa_base_usgnd.c \
	  ./ft_lstadd.c ./ft_lstadd_back.c ./ft_lstiter.c ./ft_wcharlen.c \
	  ./ft_strsplit.c ./ft_putwchar.c ./ft_wstrlen.c ./ft_putwstr.c \
	  ./ft_lstlen.c

BINAIRE = $(SRC:.c=.o)

all: $(NAME)

$(NAME): $(SRC)
	@gcc -c $(CFLAGS) $(INC) $(SRC)
	@ar rc $(NAME) $(BINAIRE)
	@ranlib $(NAME)

clean:
	@rm -f $(BINAIRE) $(INC).gch

fclean: clean
	@rm -f $(NAME)

re: fclean all
