sudo: false

language: go

env:
  - GO111MODULE=on

go:
  - 1.11

git:
  depth: false
  submodules: false

before_script:
  - go get -u github.com/bloom42/rocket
  - go get
  - make test

script:
  - make

deploy:
  provider: script
  script: rocket # use rocket to deploy
  on:
    tags: true

notifications:
  email:
    on_success: never
