sudo: required
dist: xenial

language: node_js
node_js: lts/*

before_install:
  - sudo apt-get -y install python3-pip python-dev python3-setuptools
  - pip3 install -U mkdocs

install:
  - npm install

script:
  - make lint
  - make all


deploy:
  provider: firebase
  skip_cleanup: true # Important, otherwise the build output would be purged.
  token:
    secure: $FIREBASE_TOKEN

notifications:
  email:
    on_success: never
