[Settings]


[build]
  command = "make"
  publish = "dist/"


# rewrite to for vuejs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[[redirects]]
  from = "https://inspiring-swartz-41a692/*"
  to = "https://opensource.bloom.sh/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.opensource.bloom.sh/*"
  to = "https://opensource.bloom.sh/:splat"
  status = 301
  force = true


[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    "X-XSS-Protection" = "1; mode=block"
    "X-Content-Type-Options" = "nosniff"
    "X-Download-Options" = "noopen"
    "X-Frame-Options" = "DENY"
    "Referrer-Policy" = "same-origin"
    "Expect-CT" = "max-age=86400; enforce"
    "Strict-Transport-Security" = "max-age=63072000; includeSubDomains; preload"
    "Content-Security-Policy" = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.crisp.chat; style-src 'self' 'unsafe-inline' https://*.crisp.chat https://fonts.googleapis.com; img-src 'self' data: https://bloom.sh https://*.crisp.chat https://gitlab.com https://img.shields.io https://godoc.org https://api.travis-ci.org https://travis-ci.org https://docs.rs; font-src 'self' https://*.crisp.chat https://fonts.googleapis.com  https://fonts.gstatic.com; connect-src https://*.bloom.sh https://bloom.sh wss://*.crisp.chat https://client.crisp.chat https://sentry.io/1357978 https://sentry.io/api/1357978 https://api.github.com; report-uri https://sentry.io/api/1357978/security/?sentry_key=d5082d8aa7da487db3035a70a5d9ded8"
