# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

go:
  - 1.11

git:
  depth: false
  submodules: false

before_script:
  - go get
  - make test

script:
  - make build

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  on:
    repo: z0mbie42/fswalk
    tags: true # The deployment happens only if the commit has a tag
