cache:
  untracked: true
  paths:
    - node_modules/

pages:
  image: node:lts
  only:
    - "42" # TODO: change to master + tags
  script:
    - make install
    - make build
    - mv dist public
  artifacts:
    paths:
    - public
