# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: skerkour <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2014/11/03 11:52:54 by skerkour          #+#    #+#              #
#    Updated: 2015/01/04 15:48:43 by skerkour         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
NAME	= libft.a
SRC_DIR	= misc
SRC		=	$(SRC_DIR)/ft_atoi.c \
			$(SRC_DIR)/ft_bzero.c \
			$(SRC_DIR)/ft_isalnum.c \
			$(SRC_DIR)/ft_isalpha.c \
			$(SRC_DIR)/ft_isascii.c \
			$(SRC_DIR)/ft_isdigit.c \
			$(SRC_DIR)/ft_isprint.c \
			$(SRC_DIR)/ft_memccpy.c \
			$(SRC_DIR)/ft_memchr.c \
			$(SRC_DIR)/ft_memcmp.c \
			$(SRC_DIR)/ft_memcpy.c \
			$(SRC_DIR)/ft_memmove.c \
			$(SRC_DIR)/ft_memset.c \
			$(SRC_DIR)/ft_strcat.c \
			$(SRC_DIR)/ft_strchr.c \
			$(SRC_DIR)/ft_strcpy.c \
			$(SRC_DIR)/ft_strdup.c \
			$(SRC_DIR)/ft_strlcat.c \
			$(SRC_DIR)/ft_strlen.c \
			$(SRC_DIR)/ft_strncat.c \
			$(SRC_DIR)/ft_strncpy.c \
			$(SRC_DIR)/ft_strnstr.c \
			$(SRC_DIR)/ft_strrchr.c \
			$(SRC_DIR)/ft_strstr.c \
			$(SRC_DIR)/ft_tolower.c \
			$(SRC_DIR)/ft_toupper.c \
			$(SRC_DIR)/ft_strcmp.c \
			$(SRC_DIR)/ft_strncmp.c \
			$(SRC_DIR)/ft_memalloc.c \
			$(SRC_DIR)/ft_memdel.c \
			$(SRC_DIR)/ft_strnew.c \
			$(SRC_DIR)/ft_strdel.c \
			$(SRC_DIR)/ft_strclr.c \
			$(SRC_DIR)/ft_striter.c \
			$(SRC_DIR)/ft_striteri.c \
			$(SRC_DIR)/ft_strmap.c \
			$(SRC_DIR)/ft_strmapi.c \
			$(SRC_DIR)/ft_strequ.c \
			$(SRC_DIR)/ft_strnequ.c \
			$(SRC_DIR)/ft_strsub.c \
			$(SRC_DIR)/ft_strjoin.c \
			$(SRC_DIR)/ft_strtrim.c \
			$(SRC_DIR)/ft_putchar.c \
			$(SRC_DIR)/ft_putendl.c \
			$(SRC_DIR)/ft_putstr.c \
			$(SRC_DIR)/ft_putnbr.c \
			$(SRC_DIR)/ft_putchar_fd.c \
			$(SRC_DIR)/ft_putstr_fd.c \
			$(SRC_DIR)/ft_putendl_fd.c \
			$(SRC_DIR)/ft_putnbr_fd.c \
			$(SRC_DIR)/ft_itoa.c \
			$(SRC_DIR)/ft_strsplit.c \
			$(SRC_DIR)/ft_strlenc.c \
			$(SRC_DIR)/ft_strcpyc.c \
			$(SRC_DIR)/ft_strdupc.c \
			$(SRC_DIR)/ft_memcpyb.c \
			$(SRC_DIR)/ft_memrepc.c \
			$(SRC_DIR)/ft_memreps.c \
			$(SRC_DIR)/ft_memrepi.c \
			$(SRC_DIR)/ft_memrepl.c \
			$(SRC_DIR)/ft_memdup.c \
			$(SRC_DIR)/ft_strrev.c \
			$(SRC_DIR)/ft_memrealloc.c \
			$(SRC_DIR)/ft_stack_init.c \
			$(SRC_DIR)/ft_stack_push.c \
			$(SRC_DIR)/ft_stack_pop.c \
			$(SRC_DIR)/ft_stack_peek.c \
			$(SRC_DIR)/ft_stack_destroy.c \
			$(SRC_DIR)/ft_putcharx.c \
			$(SRC_DIR)/ft_putcharx_fd.c \
			$(SRC_DIR)/ft_btree_create_node.c \
			$(SRC_DIR)/ft_btree_apply_prefix.c \
			$(SRC_DIR)/ft_btree_apply_infix.c \
			$(SRC_DIR)/ft_btree_apply_suffix.c \
			$(SRC_DIR)/ft_btree_insert_data.c \
			$(SRC_DIR)/ft_btree_search_item.c \
			$(SRC_DIR)/ft_btree_level_count.c \
			$(SRC_DIR)/ft_btree_destroy.c \
			$(SRC_DIR)/ft_buffer_dup.c \
			$(SRC_DIR)/ft_buffer_destroy.c \
			$(SRC_DIR)/ft_buffer_new.c \
			$(SRC_DIR)/ft_match.c \
			$(SRC_DIR)/ft_nmatch.c \
			$(SRC_DIR)/ft_xmalloc.c \
			$(SRC_DIR)/ft_lstpush.c \
			$(SRC_DIR)/ft_lstpop.c \
			$(SRC_DIR)/ft_lstadd_end.c \
			$(SRC_DIR)/ft_lstaddi.c \
			$(SRC_DIR)/ft_lstpeek.c \
			$(SRC_DIR)/ft_lstdel_end.c \
			$(SRC_DIR)/ft_lstdel.c \
			$(SRC_DIR)/ft_lstnew.c \
			$(SRC_DIR)/ft_lstadd_srt.c \
			$(SRC_DIR)/ft_lstadd_rev.c \
			$(SRC_DIR)/ft_strjoinf.c \
			$(SRC_DIR)/ft_strjoinff.c \
			$(SRC_DIR)/ft_lstdelone.c \
			$(SRC_DIR)/ft_lstiter.c \
			$(SRC_DIR)/ft_lstmap.c \
			$(SRC_DIR)/ft_lstrev.c \
			$(SRC_DIR)/ft_lstaddi.c \
			$(SRC_DIR)/ft_lstlen.c \
			$(SRC_DIR)/ft_lstdeli.c \
			$(SRC_DIR)/ft_count_isize.c \
			$(SRC_DIR)/ft_strcountc.c \
			$(SRC_DIR)/ft_gnl.c \
			$(SRC_DIR)/ft_perror.c \
			$(SRC_DIR)/ft_strcmpc.c \
			$(SRC_DIR)/ft_getchar.c \
			$(SRC_DIR)/ft_getchar_fd.c \
			$(SRC_DIR)/ft_arrlen.c \
			$(SRC_DIR)/ft_arrccpy.c \
			$(SRC_DIR)/ft_arrcfree.c \
			$(SRC_DIR)/ft_qsort.c
OBJ		= $(SRC:.c=.o)

RL_DIR	= ft_readline
RL_SRC	=	$(RL_DIR)/ft_readline.c \
			$(RL_DIR)/rl_putline.c \
			$(RL_DIR)/rl_movecursor.c \
			$(RL_DIR)/rl_lst.c \
			$(RL_DIR)/rl_list_to_tab.c \
			$(RL_DIR)/rl_header.c \
			$(RL_DIR)/rl_ctx.c
RL_OBJ	 = $(RL_SRC:.c=.o)

CC		= gcc
CFLAGS	= -Wall -Wextra -Werror -Ofast -march=native -I .

# **************************************************************************** #

$(NAME): $(OBJ)
	make -C $(RL_DIR)
	ar rc $(NAME) $(OBJ) $(RL_OBJ)

all: $(NAME)

.PHONY: clean fclean re

clean:
	rm -rf $(OBJ)
	make -C $(RL_DIR) clean

fclean: clean
	rm -rf $(NAME)
	make -C $(RL_DIR) fclean

re: fclean $(NAME)
