sudo: false

language: go

go:
  - 1.11

env:
  - GO111MODULE=on

git:
  depth: false
  submodules: false

install:
  - go get -u github.com/astrocorp42/flint
  - go get -u github.com/astrocorp42/rocket
  - go get

before_script:
  - make test
  - make

script:
  - make all

deploy:
  provider: script
  skip_cleanup: true # Important, otherwise the build output would be purged.
  script: rocket
  on:
    tags: true # The deployment happens only if the commit has a tag

notifications:
  email:
    on_success: never
