[package]
name = "bloom_calculator"
version = "0.1.0"
authors = ["z0mbie42 <sylvain@kerkour.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bloom_messages = { path = "../messages" }
bloom_error = { path = "../error", features = ["caldyn"] }

caldyn = { path = "../../libs/caldyn" }
