# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: skerkour <skerkour@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/06/15 19:39:32 by skerkour          #+#    #+#              #
#    Updated: 2015/06/15 19:39:56 by skerkour         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	= test

all:
	clang++ -Wall -Werror -Wextra Account.class.cpp tests.cpp -o $(NAME)

fclean:
	rm -rf $(NAME)
