image: docker:stable

services:
  - docker:dind

stages:
  - test
  - build
  - release

test:
  stage: test
  image: 'rust:1.31.1-stretch'
  tags:
    - docker
    - bloom42cicd
  script:
    - make test

build:
  stage: build
  tags:
    - docker
    - bloom42cicd
  script:
    - apk update && apk add make
    - make docker
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - make docker_push


release_docker:
  stage: release
  only:
    - tags
  tags:
    - docker
    - bloom42cicd
  script:
    - apk update && apk add make
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - make docker_release

release_crates:
  stage: release
  image: 'rust:1.31-stretch'
  only:
    - tags
  tags:
    - docker
    - bloom42cicd
  script:
    - cargo login $CRATES_TOKEN
    - cargo publish


release_github:
  stage: release
  image: 'golang:1.11-stretch'
  only:
    - tags
  tags:
    - docker
    - bloom42cicd
  script:
    - go get -u github.com/bloom42/rocket
    - rocket
