language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

script:
  # - cargo test
  - make

deploy:
  - provider: script
    skip_cleanup: true # Important, otherwise the build output would be purged.
    script: make crates_login && make crates_publish
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    on:
      tags: true

notifications:
  email:
    on_success: never
