docs_dir: pages

theme:
  name: null
  custom_dir: '../../themes/mkdocs-material/material'
  language: en
  feature:
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: /favicon.ico
  logo:
    icon: "\uE80C"
  base_url: '/signal/'

site_name: Signal
site_url: https://opensource.bloom.sh/signal/
repo_url: https://github.com/bloom42/signal/
edit_uri: https://github.com/bloom42/signal/edit/master/docs/pages/
site_dir: ../../../dist/signal


nav:
  - index.md
  - web.md
  - www.md
  - api.md
