variables:
  GO_IMAGE: golang:latest
  HUGO_VERSION: 0.62.1

pages:
  image: $GO_IMAGE
  only:
    - master
  script:
    - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
    - dpkg -i hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
    - make build
    - make gzip
  artifacts:
    paths:
    - public
