# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: skerkour <skerkour@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/03/14 18:51:15 by skerkour          #+#    #+#              #
#    Updated: 2016/03/14 19:48:01 by skerkour         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

.PHONY: all re clean fclean

NAME = computor

all:
	go build -o $(NAME)

re: clean all

clean:
	rm -rf $(NAME)

fclean: clean
