package rand

import (
	"testing"
)

func TestBytes(t *testing.T) {
	var n uint64 = 42

	data, err := Bytes(n)
	if err != nil {
		t.Error(err)
	}

	if len(data) != int(n) {
		t.Error("Generated bytes buffer is not at the expected size")
	}
}
